### PR TITLE
added: changes to header/outputwindow components

### PR DESCRIPTION
**Pull request by YousefKhalid-iq**
Added the following:
1- More colors to `tailwind.config.js`.
2- styling and timer depending on the current location to the `Header.tsx` component.
3- styling to the `OutputWindow.tsx` component.
4- added the `App.tsx` basic structure.
5- added duplicate styling from `Header.tsx` && `OutputWindow.tsx` to `App.css`.

### CODE REVIEW

**Review by AHenrikes — CHANGES_REQUESTED** [review]
Time function could be changed. Research how to do it in React.
Otherwise LGTM 👍🏽

**Comment by YousefKhalid-iq** [comment]
edit: 
Changed the js code in `Header.tsx` by using the `useEffect` && `useState` react hooks.

**Comment by YousefKhalid-iq** [comment]
edit: 
Changed the js code to a more react format in `Header.tsx`

**Review by AHenrikes — APPROVED** [review]
LGTM!! 👍🏽

**Pull request merged**
